version: '3.9'  # Use the latest supported version (3.9 as of May 10, 2024)

services:
  app:
    build: .
    volumes:
      - .:/var/www/html  # Mount your local project directory as a volume
    ports:
      - "${APP_PORT:-80}:80" # Use environment variable for port or default to 80
    environment:
      - COMPOSER_HOME=/var/www/html/vendor  # Set Composer home directory

